language: python

python:
    - 3.8

env:
    - BIDIRECTIONAL_SYNC=1
install:
    - pip install -r requirements.txt

script:
    pytest --cov-report term --cov=shortestpaths/

after_success:
    - bash <(curl https://codecov.io/bash)