{% set name = "shortestpaths" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/ThanasisMattas/shortestpaths.git

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ksp=shortestpaths.__main__:main
  include_recipe: False

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click >=7.1.2
    - numpy >=1.19.2
    - matplotlib >=3.3.2
    - scipy >=1.6.1
    - networkx >=2.5

about:
  home: https://github.com/ThanasisMattas/shortestpaths.git
  license: GNU General Public License v3 or later (LGPLv3+)
  license_family: LGPL
  license_file: COPYING
  summary: Bidirectional replacement paths and k-shortest paths search with dynamic programming

extra:
  maintainers:
    - ThanasisMattas